#index:
#    path: /
#    controller: App\Controller\DefaultController::index

api_platform:
    resource: .
    type: api_platform
    prefix: /api/v1

api_movies_digest_collection:
    path: /api/v1/movies/digest/{weekNumber}.{_format}
    requirements:
        weekNumber: '^\d{1,2}$'
    methods:
        - GET
    defaults:
        _controller: App\Controller\ApiPlatformMoviesController::digest
        _api_resource_class: App\Entity\Movie
        _api_collection_operation_name: digest
        _format: null
